spring.application.name=Hospital-Management
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_management_db

#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=qusa3187
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jps.properties.hibernate.format_sql=true